theme                 : "minimal-mistakes-jekyll"
minimal_mistakes_skin: "auqa"


locale: "UTF-8"
title: "데이터 깎는 노인"
title_separator: "-"
name: "Hussu"
description: "테스트용"
url: "https://Hussu-Joe.github.io"
baseurl: ""
repository: "Hussu-Joe/Hussu_Data"
